openapi: "3.0.0"
info:
  description: "This is the bricky API ."
  version: "1.0.0"
  title: "Bricky Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "private"
tags:
  - name: "partList"
    description: "Everything about your part lists"
  - name: "blueprint"
    description: "Everything about blueprints, aka Mocs and Sets"
  - name: "newsBlog"
    description: "Everything about newsBlog"
  - name: "user"
    description: "Operations about user"
paths:
  /partList:
    get:
      tags:
        - "partList"
      summary: "Receive all PartLists of a user"
      description: "Receive all PartLists of a user"
      responses:
        200:
          description: "OK, PartLists successfully returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartListsResponse'
  /partList/short:
    get:
      tags:
        - "partList"
      summary: "Receive all PartLists of a user only with id and name"
      description: "Receive all PartLists of a user only with id and name"
      responses:
        200:
          description: "OK, PartLists successfully returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartListsShortResponse'
  /partList/{id}:
    get:
      parameters:
        - in: path
          name: id
          description: Id of the partList
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      tags:
        - "partList"
      summary: "Receive Partlist with given Id"
      description: "Receive Partlist with given Id"
      responses:
        200:
          description: "OK, PartList successfully returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartList'
        404:
          description: "Partlist not found"
    put:
      tags:
        - "partList"
      summary: "Update an existing part list"
      description: "Update an existing part list"
      parameters:
        - in: path
          name: id
          description: Id of the partList
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartList'
      responses:
        200:
          description: "OK, PartList successfully updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartList'
        400:
          description: "At least one of the body valus is invalid"
        404:
          description: "Partlist not found"
    delete:
      tags:
        - "partList"
      summary: "Delete an existing part list"
      description: "Delete an existing part list"
      parameters:
        - in: path
          name: id
          description: Id of the partList
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: "OK, PartList successfully deleted"
        404:
          description: "Partlist not found"
  /partList/{id}/short:
    get:
      parameters:
        - in: path
          name: id
          description: Id of the partList
          required: true
          schema:
            type: string
      tags:
        - "partList"
      summary: "Receive Partlist with given Id"
      description: "Receive Partlist with given Id"
      responses:
        200:
          description: "OK, PartList successfully returned"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortPartList'
        404:
          description: "Partlist not found"
  /partList/{id}/parts:
    get:
      parameters:
        - in: path
          name: id
          description: Id of the partList
          required: true
          schema:
            type: string
      tags:
        - "partList"
      summary: "Receive Parts of the Partlist with given Id"
      description: "Receive Parts of the Partlist with given Id"
      responses:
        200:
          description: "OK, Parts successfully returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'
        404:
          description: "Partlist not found"
  /account:
          description: "Order not found"
  /blueprint/saved:
    get:
      security:
        - bearerAuth: []
      tags:
        - "blueprint"
      summary: "Get all wanted/liked blueprints by the logged in user"
      description: ""
      operationId: "getSavedBlueprints"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Blueprint"
        404:
          description: "Blueprint not found"
  /blueprint/{blueprintId}:
    get:
      tags:
        - "blueprint"
      summary: "Get details of blueprint by Id"
      description: ""
      operationId: "getBlueprintById"
      parameters:
        - name: "blueprintId"
          in: "path"
          schema:
            type: "string"
          description: "The id of the blueprint"
          required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BlueprintWithPartList"
        404:
          description: "Blueprint not found"
  /account/login:
    post:
      tags:
        - "account"
      summary: "Authorize user account"
      description: "Authenticate with Rebrickable"
      requestBody:
        $ref: '#/components/requestBodies/LoginCredentials'
      responses:
        200:
          description: "Ok, JWT Token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
          headers:
            X-Rate-Limit:
              schema:
                type: integer
              description: "calls per hour allowed by the user"
            X-Expires-After:
              schema:
                type: integer
              description: "date in UTC when token expires"
        401:
          description: "Invalid username/password supplied"
  /account/logout:
    post:
      security:
        - bearerAuth: []
      tags:
        - "account"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      parameters: []
      responses:
        200:
          description: "successful operation"
  /account/{username}:
    get:
      security:
        - bearerAuth: []
      tags:
        - "account"
      summary: "Get account info for logged in user"
      description: ""
      operationId: "getAccountByUsername"
      parameters:
        - name: "username"
          in: "path"
          schema:
            type: "string"
          description: "The username of the account you want info of"
          required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
    delete:
      security:
        - bearerAuth: []
      tags:
        - "account"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      parameters:
        - name: "username"
          in: path
          schema:
            type: string
          description: "The username of the account that needs to be deleted (can only be own)"
          required: true
      responses:
        200:
          description: "User successfully deleted"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /newsBlog/availableBlogs:
    get:
      tags:
        - "newsBlog"
      summary: "Get list of available news blogs"
      description: ""
      operationId: "getAvailableBlogs"
      parameters: []
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsBlogList'
  /newsBlog/subscribedBlogs/{username}:
    get:
      tags:
        - "newsBlog"
      summary: "Get list of subscribed news blogs"
      description: ""
      operationId: "getSubscribedBlogs"
      parameters:
        - name: "username"
          in: "path"
          schema:
            type: "string"
          description: "The username of the account you want info of"
          required: true
          example: "max_mustermann"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsBlogList'
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"

  /newsBlog/subscription/{username}/{blogId}:
    put:
      tags:
        - "newsBlog"
      summary: "put given Blog to list of subscribed news blogs"
      description: ""
      operationId: "subscribeBlog"
      parameters:
        - name: "username"
          in: "path"
          schema:
            type: "string"
          description: "The username of the account you want to subscribe"
          required: true
          example: "max_mustermann"
        - name: "blogId"
          in: "path"
          schema:
            type: integer
            format: int64
          description: "The id of the news blog you want to subscribe"
          required: true
          example: 5
      responses:
        200:
          description: "Subscription successfully added"
        400:
          description: "Invalid username or blogId supplied"
        404:
          description: "User or NewsBlog not found"
    delete:
      tags:
        - "newsBlog"
      summary: "delete given Blog from list of subscribed news blogs"
      description: ""
      operationId: "unsubscribeBlog"
      parameters:
        - name: "username"
          in: "path"
          schema:
            type: "string"
          description: "The username of the account you want to unsubscribe"
          required: true
          example: "max_mustermann"
        - name: "blogId"
          in: "path"
          schema:
            type: integer
            format: int64
          description: "The id of the news blog you want to unsubscribe"
          required: true
          example: 5
      responses:
        200:
          description: "Subscription successfully deleted"
        400:
          description: "Invalid username or blogId supplied"
        404:
          description: "User or NewsBlog not found"
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  requestBodies:
    LoginCredentials:
      description: "Login Credentials"
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginScheme'
          example:
            username: "Dönermann"
            password: "Kebab"
  schemas:
    LoginScheme:
      type: object
      properties:
        username:
          type: "string"
        password:
          type: "string"
    PartListsResponse:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/PartList'
    PartListsShortResponse:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/ShortPartList'
    Account:
      type: "object"
      properties:
        username:
          type: "string"
    ResponseToken:
      type: "object"
      properties:
        app_token:
          type: "string"
          example: "32okdwkdwkoa2"
    Part:
      type: "object"
      properties:
        partNumber:
          type: "integer"
          format: "int32"
        partId:
          type: "string"
        name:
          type: "string"
        print:
          type: "string"
        category:
          type: "string"
        imgUrl:
          type: "string"
        color:
          type: "string"
      example:
        partNumber: 123
        partId: "1x2 Block"
        name: "1x2 Block"
        print: "blue123"
        category: "Kebab"
        imgUrl: "http://image.de"
        color: "red"
    PartList:
      type: "object"
      properties:
        listId:
          type: "integer"
          format: "int64"
          example: 12
        name:
          type: "string"
          example: "My List"
        blueprint:
          $ref: '#/components/schemas/Blueprint'
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
    ShortPartList:
      type: "object"
      properties:
        listId:
          type: "integer"
          format: "int64"
          example: 12
        name:
          type: "string"
          example: "My List"
        blueprint:
          $ref: '#/components/schemas/Blueprint'
    BlueprintType:
      type: "string"
      enum:
        - MOC
        - SET
    Blueprint:
      type: "object"
      properties:
        blueprintId:
          type: "integer"
          format: "int64"
        theme:
          type: "string"
        name:
          type: "string"
        author:
          type: "string"
        imgUrl:
          type: "string"
        type:
          $ref: '#/components/schemas/BlueprintType'
    BlueprintWithPartList:
      allOf:
        - $ref: '#/components/schemas/Blueprint'
        - type: object
      properties:
        partlist:
          $ref: '#/components/schemas/PartList'
    NewsBlog:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        url:
          type: "string"
        author:
          type: "string"
      example:
        id: 1
        name: zusammengebaut
        url: https://zusammengebaut.com/
        author: mehrere
    NewsBlogList:
     type: object
     properties:
        newsBlogs:
          type: array
          items:
            $ref: '#/components/schemas/NewsBlog'
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"